//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public int id { get; set; }
        public string TransactionNo { get; set; }
        public long productID { get; set; }
        public long Quantity { get; set; }
        public System.DateTime Date { get; set; }
        public double Price { get; set; }
        public string Status { get; set; }
    
        public virtual product product { get; set; }
    }
}
