//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockin
    {
        public int id { get; set; }
        public string ReferenceNo { get; set; }
        public long Quantity { get; set; }
        public System.DateTime InDate { get; set; }
        public string StockInBy { get; set; }
        public long productId { get; set; }
        public string ProductDescription { get; set; }
    
        public virtual product product { get; set; }
    }
}
